### ISSUE TITLE
Vueのチュートリアル

### ISSUE THREAD

**Issue by takuuuuumi34** [xxxcreation/BackpackStation#6]
# Why

Vueの使い方を理解する.
特にコンポーネントの項目.

# Who

開発者

# 優先度

5

# 完了条件

- [ ] Vueのチュートリアルをやる

**Comment by wtrmgmg** [comment]
wtrmgmg/train ブランチにチュートリアル消化がてらTodoを作成
割と今週分はもういいかなと思っている
