### ISSUE TITLE
1stリリースに向けた機能洗い出し

### ISSUE THREAD

**Issue by takuuuuumi34** [xxxcreation/BackpackStation#9]
# Why

時期バージョンの開発方針とタスクを洗い出すため

# Who

開発者

# 優先度

5

# 完了条件
- [x] オーナーに必要な機能を洗い出す 
- [x]  一般ユーザに必要な機能を洗い出す
- [x] airbnbから取得する情報を洗い出す

**Comment by Satoshi1201** [comment]
Airbnbから取得する情報やけど
価格がもしかすると、土日の価格とかで正確にとれるか怪しい。日付検索で合計金額（ただし、清掃費は一回の滞在につき一度だけなので、その辺のロジックを書くのに多少頭を使う必要があるかも）を取得できれば良いかも。
